EXTRACTED_PATH = "./Extracted Data"
FOLLOWERS_PATH = EXTRACTED_PATH + "/followers_and_following/followers_1"
FOLLOWING_PATH = EXTRACTED_PATH + "/followers_and_following/following"
JSON = ".json"
HTML = ".html"
